### ISSUE TITLE
Request About the Classification of MetaICL Model in Project

### ISSUE THREAD

**Issue by SeanAlpaca818** [mukhal/icl-ensembling#2]
Hi,

I've encountered some issues while running the code and noticed that the MetaICLModel class initialization doesn't accept the ensemble_method parameter. To better understand and resolve this issue, I have a few questions:

Is the MetaICLModel class used in the code directly from the [MetaICL](https://github.com/facebookresearch/MetaICL) project?
If so, has it been modified or customized in any way?
Could you provide the specific definition of the MetaICLModel class or any relevant documentation so that I can understand how to properly initialize this class?

Thank you very much for your help!

**Comment by mukhal** [comment]
Hey, thank you for you interest! 

Our custom metaicl module was not uploaded to the repo. I just pushed it, so it should work now. Apologies for that!
